### ISSUE TITLE
catkin compile error

### ISSUE THREAD

**Issue by arpit15** [personalrobotics/dart_examples#7]
This code is failing to compile with aikido due to restructuring of util to common and io.
Can you kindly list the commit of the aikido with which code works?

**Comment by jslee02** [comment]
@brianhou Are we maintaining this repo? If so, I think it would make sense to have these examples in AIKIDO repository to maintain this along with AIKIDO.

**Comment by brianhou** [comment]
I think it'd be nice to update this repository enough that it compiles. I don't think there's really anything significant in these examples that isn't already in libherb or pantry_loading / herb3_demos, so I don't think it's necessary to merge this into AIKIDO.

@arpit15 I think https://github.com/personalrobotics/aikido/commit/2c24a9bd10a8412084d8979a4995a81fd4103259 is the commit that splits the util namespace. The one before it (https://github.com/personalrobotics/aikido/commit/5dfb604c4cb89b9ef521f72f71329d0756f83ea1) might work.

**Comment by brianhou** [comment]
Actually scratch that, that commit won't work. I'll try to PR a fix soon.

**Comment by brianhou** [comment]
@arpit15 this should be fixed now with the current master branches of this repo and AIKIDO. Let us know if you run into any further issues!

**Comment by arpit15** [comment]
I am still getting an aikido error
 Could NOT find aikido (missing: rviz) (Required is at least version
  "0.2.0")

**Comment by jslee02** [comment]
Please make sure all [the dependencies](https://github.com/personalrobotics/aikido/blob/master/src/rviz/CMakeLists.txt#L1-L22) are installed when you build AIKIDO. If a necessary dependency is not installed, you might see some warning messages in running `cmake ..` (or `catkin build --verbose`).

**Comment by arpit15** [comment]
@jslee02 I checked for the dependencies. I am able to build aikido without any errors. However aikido installation doesn't generate aikido_rvizComponent.cmake file it does for other submodules like aikido_ioComponent.cmake which I think is causing the error
[This](https://gist.github.com/arpit15/12346f455401846630ddad7fe71143da) is the output of catkin build --verbose.

**Comment by jslee02** [comment]
It's not errors but warnings. `aikido-rviz` component is optional, and it's not built with warnings if all the dependencies are not installed. 

Could you please post the cmake outputs of **AIKIDO** not `dart_example`'s? For sure, it would be good to rebuild after `catkin clean`.
